name: specseq
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - bedtools=2.30.0
  - samtools=1.10
  - python=3.8
  - last=1250
  - pip
  - wheel
  - graphviz
  - conda-forge::r-base<4
  - conda-forge::r-tidyverse=1.3.1
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-forcats=0.5.1
  - conda-forge::r-ggthemes=4.2.4
  - conda-forge::r-patchwork=1.1.1
  - augustus=3.3.3
  - diamond=2.0.6
  - pip:
    - bdsg
